import { NextResponse } from "next/server";
import { StockMovementType } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/backend/lib/prisma";
import { canWrite } from "@/backend/lib/context";
import { requireApiContext, jsonError, decimalToNumber } from "@/backend/lib/http";
import { audit } from "@/backend/lib/audit";
const schema=z.object({itemId:z.string(),type:z.enum(StockMovementType),quantity:z.coerce.number().positive(),unitCost:z.coerce.number().nonnegative().nullable().optional(),reason:z.string().max(300).nullable().optional()});
export async function POST(request:Request){const auth=await requireApiContext();if("error" in auth)return auth.error;if(!canWrite(auth.ctx.membership.role))return jsonError("Sem permissão",403);const p=schema.safeParse(await request.json().catch(()=>null));if(!p.success)return jsonError("Dados inválidos");const item=await prisma.inventoryItem.findFirst({where:{id:p.data.itemId,restaurantId:auth.ctx.restaurant.id}});if(!item)return jsonError("Item inválido");let next=Number(item.currentStock);const previous=next;if(p.data.type==="IN")next+=p.data.quantity;else if(p.data.type==="OUT")next-=p.data.quantity;else next=p.data.quantity;if(next<0)return jsonError("Estoque não pode ficar negativo");const result=await prisma.$transaction(async tx=>{const movement=await tx.stockMovement.create({data:{restaurantId:auth.ctx.restaurant.id,...p.data}});const update:any={currentStock:next};if(p.data.type==="IN"&&p.data.unitCost!=null){const oldValue=previous*Number(item.averageCost);const addedValue=p.data.quantity*p.data.unitCost;update.averageCost=next>0?(oldValue+addedValue)/next:p.data.unitCost;}await tx.inventoryItem.update({where:{id:item.id},data:update});return movement});await audit({restaurantId:auth.ctx.restaurant.id,actorUserId:auth.ctx.user.id,action:"STOCK_MOVEMENT",entity:"InventoryItem",entityId:item.id,data:p.data});return NextResponse.json(decimalToNumber(result),{status:201});}
