import { NextResponse } from "next/server";
import { PaymentMethod } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/backend/lib/prisma";
import { canManage, canWrite } from "@/backend/lib/context";
import { requireApiContext, jsonError, decimalToNumber } from "@/backend/lib/http";
import { audit } from "@/backend/lib/audit";
import { refsBelongToRestaurant } from "@/backend/lib/ownership";
const paySchema=z.object({action:z.literal("PAY"),paidAt:z.coerce.date().optional(),paymentMethod:z.enum(PaymentMethod),accountId:z.string().nullable().optional()});
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireApiContext();if("error" in auth)return auth.error;if(!canWrite(auth.ctx.membership.role))return jsonError("Sem permissão",403);const {id}=await params;const p=paySchema.safeParse(await request.json().catch(()=>null));if(!p.success)return jsonError("Dados inválidos");if(!(await refsBelongToRestaurant(auth.ctx.restaurant.id,{accountId:p.data.accountId})))return jsonError("Conta inválida",403);const payable=await prisma.accountsPayable.findFirst({where:{id,restaurantId:auth.ctx.restaurant.id}});if(!payable)return jsonError("Conta não encontrada",404);if(payable.status==="PAID")return jsonError("Esta conta já foi paga");const paidAt=p.data.paidAt||new Date();const result=await prisma.$transaction(async tx=>{const movement=await tx.transaction.create({data:{restaurantId:auth.ctx.restaurant.id,createdByUserId:auth.ctx.user.id,type:"EXPENSE",description:payable.description,amount:payable.amount,occurredAt:paidAt,paymentMethod:p.data.paymentMethod,categoryId:payable.categoryId,accountId:p.data.accountId||payable.accountId,notes:`Baixa automática da conta a pagar ${payable.id}`,reference:`PAYABLE:${payable.id}`}});return tx.accountsPayable.update({where:{id},data:{status:"PAID",paidAt,paymentMethod:p.data.paymentMethod,accountId:p.data.accountId||payable.accountId,transactionId:movement.id}});});await audit({restaurantId:auth.ctx.restaurant.id,actorUserId:auth.ctx.user.id,action:"PAY",entity:"AccountsPayable",entityId:id,data:{paymentMethod:p.data.paymentMethod,paidAt}});return NextResponse.json(decimalToNumber(result));}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireApiContext();if("error" in auth)return auth.error;if(!canManage(auth.ctx.membership.role))return jsonError("Sem permissão",403);const {id}=await params;const row=await prisma.accountsPayable.findFirst({where:{id,restaurantId:auth.ctx.restaurant.id}});if(!row)return jsonError("Conta não encontrada",404);if(row.status==="PAID")return jsonError("Não exclua conta paga; estorne a movimentação com procedimento de auditoria",409);await prisma.accountsPayable.delete({where:{id}});await audit({restaurantId:auth.ctx.restaurant.id,actorUserId:auth.ctx.user.id,action:"DELETE",entity:"AccountsPayable",entityId:id,data:decimalToNumber(row)});return NextResponse.json({ok:true});}
