import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/backend/lib/prisma";
import { canWrite } from "@/backend/lib/context";
import { requireApiContext, jsonError, decimalToNumber } from "@/backend/lib/http";
import { audit } from "@/backend/lib/audit";
import { refsBelongToRestaurant } from "@/backend/lib/ownership";
const schema=z.object({description:z.string().min(2).max(180),amount:z.coerce.number().positive(),dueDate:z.coerce.date(),supplierId:z.string().nullable().optional(),categoryId:z.string().nullable().optional(),accountId:z.string().nullable().optional(),notes:z.string().max(1000).nullable().optional()});
export async function GET(){const auth=await requireApiContext();if("error" in auth)return auth.error;const now=new Date();await prisma.accountsPayable.updateMany({where:{restaurantId:auth.ctx.restaurant.id,status:"PENDING",dueDate:{lt:new Date(now.getFullYear(),now.getMonth(),now.getDate())}},data:{status:"OVERDUE"}});const rows=await prisma.accountsPayable.findMany({where:{restaurantId:auth.ctx.restaurant.id},orderBy:[{status:"asc"},{dueDate:"asc"}],include:{supplier:true,category:true,account:true,creator:{select:{name:true}}}});return NextResponse.json(decimalToNumber(rows));}
export async function POST(request:Request){const auth=await requireApiContext();if("error" in auth)return auth.error;if(!canWrite(auth.ctx.membership.role))return jsonError("Sem permissão",403);const p=schema.safeParse(await request.json().catch(()=>null));if(!p.success)return jsonError("Dados inválidos");if(!(await refsBelongToRestaurant(auth.ctx.restaurant.id,{supplierId:p.data.supplierId,categoryId:p.data.categoryId,accountId:p.data.accountId})))return jsonError("Fornecedor, categoria ou conta inválido",403);const row=await prisma.accountsPayable.create({data:{restaurantId:auth.ctx.restaurant.id,createdByUserId:auth.ctx.user.id,...p.data,supplierId:p.data.supplierId||null,categoryId:p.data.categoryId||null,accountId:p.data.accountId||null}});await audit({restaurantId:auth.ctx.restaurant.id,actorUserId:auth.ctx.user.id,action:"CREATE",entity:"AccountsPayable",entityId:row.id,data:p.data});return NextResponse.json(decimalToNumber(row),{status:201});}
