"use client";
import { FormEvent, useEffect, useState } from "react";
type Account={id:string;name:string;type:string};
type Session={id:string;status:string;openingBalance:number;closingCounted:number|null;expectedBalance:number;difference:number|null;openedAt:string;closedAt?:string|null;account:Account;openedBy:{name:string};closedBy?:{name:string}|null};
function brl(n:number){return n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
export default function CashClient(){
 const[rows,setRows]=useState<Session[]>([]);const[accounts,setAccounts]=useState<Account[]>([]);
 async function load(){const[a,b]=await Promise.all([fetch("/api/cash-sessions"),fetch("/api/reference")]);if(a.ok)setRows(await a.json());if(b.ok)setAccounts((await b.json()).accounts.filter((x:Account)=>x.type==="CASH"))}
 useEffect(()=>{load()},[]);
 async function open(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const r=await fetch("/api/cash-sessions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accountId:f.get("accountId"),openingBalance:f.get("openingBalance"),notes:f.get("notes")||null})});if(!r.ok){alert((await r.json()).error);return}form.reset();load()}
 async function close(row:Session){const counted=prompt(`Saldo esperado: ${brl(row.expectedBalance)}\nQuanto foi contado fisicamente?`);if(counted==null)return;const r=await fetch(`/api/cash-sessions/${row.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({closingCounted:counted})});if(!r.ok){alert((await r.json()).error);return}const d=await r.json();alert(`Caixa fechado. Diferença: ${brl(d.difference)}`);load()}
 return <main className="content"><h1 className="page-title">Abertura e fechamento de caixa</h1><p className="page-subtitle">Compare o valor contado com o saldo esperado pelas movimentações registradas.</p><div className="card"><form className="form-grid" onSubmit={open}><div className="field"><label>Caixa</label><select name="accountId" required><option value="">Selecione</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>Fundo de abertura</label><input name="openingBalance" type="number" step="0.01" min="0" required/></div><div className="field span-2"><label>Observação</label><input name="notes"/></div><div className="span-4"><button className="btn primary">Abrir caixa</button></div></form></div><div className="card" style={{marginTop:16}}><div className="table-wrap"><table><thead><tr><th>Abertura</th><th>Caixa</th><th>Operador</th><th>Status</th><th>Abertura</th><th>Esperado</th><th>Contado</th><th>Diferença</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.openedAt).toLocaleString("pt-BR")}</td><td>{x.account.name}</td><td>{x.openedBy.name}</td><td><span className={`badge ${x.status==="CLOSED"?"paid":"pending"}`}>{x.status}</span></td><td>{brl(x.openingBalance)}</td><td>{brl(x.expectedBalance)}</td><td>{x.closingCounted==null?"—":brl(x.closingCounted)}</td><td>{x.difference==null?"—":brl(x.difference)}</td><td>{x.status==="OPEN"&&<button className="btn small primary" onClick={()=>close(x)}>Fechar</button>}</td></tr>)}</tbody></table></div></div></main>
}
